"""Read the `@feature` directives off the test suite and write the coverage table."""

import argparse
import ast
import difflib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_FEATURES = REPO_ROOT / "docs/features.md"
DEFAULT_OUTPUT = REPO_ROOT / "docs/coverage.md"

BACKEND_GLOBS = ["insights/**/test_*.py"]
UNIT_GLOBS = ["frontend/src2/**/*.test.ts", "frontend/src2/**/*.spec.ts"]
E2E_GLOBS = ["frontend/e2e/tests/*.spec.ts"]

LAYERS = ("backend", "unit", "e2e")

SLUG = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*\.[a-z0-9]+(?:-[a-z0-9]+)*$")
DIRECTIVE = re.compile(r"^\s*(?://|#)\s*@feature\s+(.+?)\s*$")
TS_TEST = re.compile(
    r"^\s*(?:it|test)"
    r"(?:\.(?:skip|only|todo|fails|concurrent|sequential))?"
    r"(?:\.each\s*(?:\(.*\)|`.*`))?"
    r"\s*\("
)
TS_TITLE = re.compile(r"""^\s*(['"`])(.*?)(?<!\\)\1""")


class Feature:
    def __init__(self, area, slug, sentence):
        self.area = area
        self.slug = slug
        self.sentence = sentence
        self.tests = {layer: [] for layer in LAYERS}


class Test:
    def __init__(self, path, line, name, layer, slugs):
        self.path = path
        self.line = line
        self.name = name
        self.layer = layer
        self.slugs = slugs

    @property
    def label(self):
        if self.layer == "backend":
            return f"{self.path}::{self.name}"
        if self.layer == "unit":
            return f'{self.path}::"{self.name}"'
        return f'"{self.name}"'


def read_features(path):
    features = {}
    area = None
    for line in path.read_text().splitlines():
        heading = re.match(r"^##\s+(.+?)\s*$", line)
        if heading:
            area = heading.group(1)
            continue
        if not line.startswith("|") or area is None:
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) < 2 or not SLUG.match(cells[0]):
            continue
        features[cells[0]] = Feature(area, cells[0], cells[1])
    return features


def directive_slugs(lines, index):
    if index <= 0:
        return None
    match = DIRECTIVE.match(lines[index - 1])
    return match.group(1).split() if match else None


def read_python_tests(path, relative):
    lines = path.read_text().splitlines()
    tree = ast.parse("\n".join(lines), filename=str(path))
    bodies = [tree.body]
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            bodies.append(node.body)
    tests = []
    for body in bodies:
        for node in body:
            if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
                continue
            if not node.name.startswith("test_"):
                continue
            tests.append(
                Test(relative, node.lineno, node.name, "backend", directive_slugs(lines, node.lineno - 1))
            )
    return tests


def ts_title(lines, index, after_paren):
    rest = after_paren
    cursor = index
    while not rest.strip():
        cursor += 1
        if cursor >= len(lines):
            return None
        rest = lines[cursor]
    match = TS_TITLE.match(rest)
    return match.group(2) if match else None


def read_ts_tests(path, relative, layer):
    lines = path.read_text().splitlines()
    tests = []
    for index, line in enumerate(lines):
        match = TS_TEST.match(line)
        if not match:
            continue
        title = ts_title(lines, index, line[match.end() :])
        if title is None:
            continue
        tests.append(Test(relative, index + 1, title, layer, directive_slugs(lines, index)))
    return tests


def collect(root, globs):
    return sorted({match for glob in globs for match in root.glob(glob)})


def read_tests(root):
    tests = []
    for path in collect(root, BACKEND_GLOBS):
        tests.extend(read_python_tests(path, path.relative_to(root).as_posix()))
    for path in collect(root, UNIT_GLOBS):
        tests.extend(read_ts_tests(path, path.relative_to(root).as_posix(), "unit"))
    for path in collect(root, E2E_GLOBS):
        tests.extend(read_ts_tests(path, path.relative_to(root).as_posix(), "e2e"))
    return tests


def cell(text):
    return text.replace("|", "\\|")


def render(features, tests):
    unknown = []
    undirected = []
    for test in tests:
        if test.slugs is None:
            undirected.append(test)
            continue
        for slug in test.slugs:
            if slug in features:
                features[slug].tests[test.layer].append(test)
            else:
                unknown.append((slug, test))

    areas = {}
    for feature in features.values():
        areas.setdefault(feature.area, []).append(feature)

    out = ["# Coverage", ""]
    out.append(
        "Generated by `insights/tests/features.py` from the `@feature` directives. Do not edit by hand."
    )
    out += ["", "## Summary", "", "| Area | Rows | Any test | E2E | None |", "|---|---|---|---|---|"]

    totals = [0, 0, 0, 0]
    for area, rows in areas.items():
        counts = [
            len(rows),
            sum(1 for row in rows if any(row.tests[layer] for layer in LAYERS)),
            sum(1 for row in rows if row.tests["e2e"]),
            sum(1 for row in rows if not any(row.tests[layer] for layer in LAYERS)),
        ]
        totals = [total + count for total, count in zip(totals, counts, strict=True)]
        out.append(f"| {area} | " + " | ".join(str(count) for count in counts) + " |")
    out.append("| **Total** | " + " | ".join(f"**{total}**" for total in totals) + " |")

    for area, rows in areas.items():
        out += ["", f"## {area}", "", "| Slug | Feature | Backend | Unit | E2E |", "|---|---|---|---|---|"]
        for row in rows:
            cells = ["<br>".join(cell(test.label) for test in row.tests[layer]) for layer in LAYERS]
            out.append(f"| {row.slug} | {cell(row.sentence)} | " + " | ".join(cells) + " |")

    out += ["", "## Unknown slugs", ""]
    if unknown:
        out += [f"- `{slug}` — {test.path}:{test.line}" for slug, test in unknown]
    else:
        out.append("None.")

    out += ["", "## Tests without a directive", ""]
    if undirected:
        out += [f"- {test.path}:{test.line} — {test.name}" for test in undirected]
    else:
        out.append("None.")

    missing = [row.slug for row in features.values() if not any(row.tests[layer] for layer in LAYERS)]
    out += ["", "## Features without a test", ""]
    out += [f"- `{slug}`" for slug in missing] if missing else ["None."]

    return "\n".join(out) + "\n", unknown, undirected, missing


def generate(features_path, root):
    return render(read_features(features_path), read_tests(root))


def main(argv=None):
    parser = argparse.ArgumentParser(prog="features.py")
    parser.add_argument("command", choices=("generate", "check"))
    parser.add_argument("--features", type=Path, default=DEFAULT_FEATURES)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    args = parser.parse_args(argv)

    coverage, unknown, undirected, missing = generate(args.features, args.root)

    if args.command == "generate":
        args.output.write_text(coverage)
        print(f"{args.output}: {coverage.count(chr(10))} lines")
        print(f"unknown slugs: {len(unknown)}, tests without a directive: {len(undirected)}")
        print(f"features without a test: {len(missing)}")
        return 0

    failed = False
    checked_in = args.output.read_text() if args.output.exists() else ""
    if checked_in != coverage:
        diff = difflib.unified_diff(
            checked_in.splitlines(keepends=True),
            coverage.splitlines(keepends=True),
            fromfile=f"{args.output} (checked in)",
            tofile=f"{args.output} (generated)",
        )
        sys.stdout.writelines(diff)
        print(f"\n{args.output} is out of date. Run: python insights/tests/features.py generate")
        failed = True
    for slug, test in unknown:
        print(f"{test.path}:{test.line}: unknown slug `{slug}`")
        failed = True
    for test in undirected:
        print(f"{test.path}:{test.line}: {test.name} has no @feature directive")
        failed = True
    if missing:
        print(f"{len(missing)} features have no test.")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
