"""The vocabulary gate: the retired words stay retired.

`CONTEXT.md` retired two words. "Bundle" was the name for a container we
invented to hold shipped content, and that container is the workbook itself
now. `logical_id` said what the field is not, where `standard_id` states the
rule: only standard content has one.

A rename is easy to land and easy to leak back — one merge, one new call site,
and the tree speaks both vocabularies again. This test is what makes the rename
hold. It reads source files, needs no database, and fails naming the file and
line so the fix is obvious.
"""

import os
import re
import unittest

import frappe

# The word is retired for the shipping unit, not for every meaning. A JavaScript
# asset bundle is Frappe's word and stays. So the gate cannot be a pattern: it is
# a literal list of the lines that survive, each with the reason it does.
#
# Keep it literal. A pattern permissive enough to admit `*.bundle.js` would also
# admit a sync module that happens to ship one, which is the thing being guarded.
EXEMPTIONS = {
    # a JavaScript asset bundle — Frappe's word, not ours
    "insights/hooks.py": ["insights_nudge.bundle.js"],
    "frontend/src2/query/helpers.ts": ["into the island bundle"],
    "frontend/src2/helpers/navigation.ts": ["drags every routed page into the bundle"],
    # A registered patch filename is frozen: renaming one re-runs it on every
    # site that already ran it. These two carry the old words in their names,
    # and the rename patch has to name the field it renames from.
    "insights/patches.txt": [
        "move_bundle_containers_to_logical_id",
        "rename_logical_id_to_standard_id",
    ],
    "insights/patches/rename_logical_id_to_standard_id.py": ["logical_id"],
    "insights/patches/move_bundle_containers_to_logical_id.py": [
        # the site global's key is data sitting in real databases, not an
        # identifier — changing it makes the patch a no-op on the sites that
        # need it
        "insights_bundle_workbook:",
        "The file name still says",
    ],
}

# Directories under the scanned roots that are not source.
SKIPPED = (
    "insights/public",  # build output, and the nudge asset itself
    "insights/locale",  # generated; regenerated by its own chore commit
    "__pycache__",
    "node_modules",
)

SCANNED_SUFFIXES = (".py", ".ts", ".vue", ".json", ".txt", ".js")

# the gate has to name what it forbids
GATE = "insights/tests/test_vocabulary.py"

RETIRED = re.compile(r"bundle|logical_id", re.IGNORECASE)


def app_root() -> str:
    return os.path.dirname(frappe.get_app_path("insights"))


def source_files():
    for root in ("insights", "frontend/src2"):
        for dirpath, dirnames, filenames in os.walk(os.path.join(app_root(), root)):
            relative_dir = os.path.relpath(dirpath, app_root())
            if any(part in relative_dir for part in SKIPPED):
                dirnames[:] = []
                continue
            for filename in sorted(filenames):
                if not filename.endswith(SCANNED_SUFFIXES):
                    continue
                path = os.path.join(dirpath, filename)
                relative_path = os.path.relpath(path, app_root())
                if relative_path == GATE:
                    continue
                yield relative_path, path


def offences():
    """Every line carrying a retired word that no exemption covers."""
    found = []
    for relative_path, path in source_files():
        allowed = EXEMPTIONS.get(relative_path, [])
        try:
            with open(path, encoding="utf-8") as f:
                lines = f.readlines()
        except UnicodeDecodeError:
            continue
        for number, line in enumerate(lines, start=1):
            if RETIRED.search(line) and not any(reason in line for reason in allowed):
                found.append(f"{relative_path}:{number}: {line.strip()}")
    return found


class TestRetiredVocabulary(unittest.TestCase):
    def test_no_source_file_speaks_the_retired_vocabulary(self):
        found = offences()
        self.assertEqual(
            found,
            [],
            "These lines use a retired word. The shipping unit is a workbook and "
            "the identity field is `standard_id`. If a line is a JavaScript asset "
            "bundle or a frozen patch filename, add it to EXEMPTIONS with its "
            "reason:\n  " + "\n  ".join(found),
        )

    def test_every_exemption_is_still_earning_its_place(self):
        """An exemption outlives the line it excused, and then it is a hole.

        The list is small and hand-written, so it is worth asserting that each
        entry still matches something — an exemption nobody can see is one
        nobody will remove.
        """
        stale = []
        for relative_path, reasons in EXEMPTIONS.items():
            path = os.path.join(app_root(), relative_path)
            if not os.path.isfile(path):
                stale.append(f"{relative_path} (file is gone)")
                continue
            with open(path, encoding="utf-8") as f:
                content = f.read()
            for reason in reasons:
                if reason not in content:
                    stale.append(f"{relative_path}: {reason!r}")

        self.assertEqual(stale, [], f"EXEMPTIONS entries that match nothing any more: {stale}")
